FACTION_DATA = {   'corporate_guard': {   'control': 50,
                           'description': 'Remnants of a pre-apocalypse '
                                          'corporation, seeking to restore '
                                          'order through force.',
                           'faction_boss': {   'damage_multiplier': 3.0,
                                               'hp_multiplier': 4.0,
                                               'name': 'Commander Valerius',
                                               'vehicle': 'hatchback'},
                           'hub_city_coordinates': [25, 50],
                           'name': 'Corporate Guard',
                           'relationships': {   'desert_rats': 'Hostile',
                                                'the_convoy': 'Hostile',
                                                'the_junction': 'Neutral',
                                                'the_vultures': 'Hostile'},
                           'units': ['sedan', 'armored_truck', 'peacekeeper']},
    'desert_rats': {   'control': 50,
                       'description': 'Nomadic speed demons who value freedom '
                                      'and fast cars above all else.',
                       'faction_boss': {   'damage_multiplier': 3.5,
                                           'hp_multiplier': 3.0,
                                           'name': 'Road Captain Fury',
                                           'vehicle': 'sports_car'},
                       'hub_city_coordinates': [40, -20],
                       'name': 'Desert Rats',
                       'relationships': {   'corporate_guard': 'Hostile',
                                            'the_convoy': 'Allied',
                                            'the_junction': 'Neutral',
                                            'the_vultures': 'Hostile'},
                       'units': ['motorcycle', 'hotrod', 'muscle_car']},
    'the_convoy': {   'control': 50,
                      'description': 'A massive, mobile city of traders and '
                                     'merchants, always on the move.',
                      'faction_boss': {   'damage_multiplier': 2.0,
                                          'hp_multiplier': 6.0,
                                          'name': 'The Quartermaster',
                                          'vehicle': 'truck'},
                      'hub_city_coordinates': [-40, -35],
                      'name': 'The Convoy',
                      'relationships': {   'corporate_guard': 'Hostile',
                                           'desert_rats': 'Allied',
                                           'the_junction': 'Neutral',
                                           'the_vultures': 'Neutral'},
                      'units': ['truck', 'van', 'panel_wagon']},
    'the_junction': {   'control': 100,
                        'description': 'A neutral oasis of commerce and '
                                       'diplomacy in the heart of the '
                                       'wasteland.',
                        'faction_boss': None,
                        'hub_city_coordinates': [0, 0],
                        'name': 'The Junction',
                        'relationships': {   'corporate_guard': 'Neutral',
                                             'desert_rats': 'Neutral',
                                             'the_convoy': 'Neutral',
                                             'the_vultures': 'Neutral'},
                        'units': ['rusty_sedan', 'guard_truck']},
    'the_vultures': {   'control': 50,
                        'description': 'Vicious scavengers who live by the '
                                       'creed of might makes right.',
                        'faction_boss': {   'damage_multiplier': 2.5,
                                            'hp_multiplier': 5.0,
                                            'name': 'Scrap King Klaw',
                                            'vehicle': 'war_rig'},
                        'hub_city_coordinates': [-30, 30],
                        'name': 'The Vultures',
                        'relationships': {   'corporate_guard': 'Hostile',
                                             'desert_rats': 'Hostile',
                                             'the_convoy': 'Neutral',
                                             'the_junction': 'Neutral'},
                        'units': ['rust_bucket', 'raider_buggy', 'technical']}}
