FACTION_DATA = {   'aether_syndicate': {   'control': 40,
                            'faction_boss': {   'damage_multiplier': 2.0,
                                                'hp_multiplier': 3.5,
                                                'name': 'Synthotic Siren',
                                                'vehicle': 'Technical'},
                            'hub_city_coordinates': [0, 40],
                            'name': 'Aether Syndicate',
                            'relationships': {   'iron_pioneers': 'Neutral',
                                                 'neon_runners': 'Neutral',
                                                 'scrap_vultures': 'Hostile',
                                                 'the_junction': 'Neutral'},
                            'units': ['PanelWagon', 'Vehicle']},
    'iron_pioneers': {   'control': 30,
                         'faction_boss': {   'damage_multiplier': 4.0,
                                             'hp_multiplier': 6.0,
                                             'name': 'Scrap Sire',
                                             'vehicle': 'WarRig'},
                         'hub_city_coordinates': [50, 10],
                         'name': 'Iron Pioneers',
                         'relationships': {   'aether_syndicate': 'Neutral',
                                              'neon_runners': 'Neutral',
                                              'scrap_vultures': 'Neutral',
                                              'the_junction': 'Neutral'},
                         'units': ['Truck', 'Van']},
    'neon_runners': {   'control': 60,
                        'faction_boss': {   'damage_multiplier': 3.0,
                                            'hp_multiplier': 4.0,
                                            'name': 'Neon Siren',
                                            'vehicle': 'Hotrod'},
                        'hub_city_coordinates': [-50, 20],
                        'name': 'Neon Runners',
                        'relationships': {   'aether_syndicate': 'Neutral',
                                             'iron_pioneers': 'Neutral',
                                             'scrap_vultures': 'Hostile',
                                             'the_junction': 'Neutral'},
                        'units': ['Hotrod', 'PanelWagon', 'SportsCar']},
    'the_junction': {   'control': 80,
                        'faction_boss': None,
                        'hub_city_coordinates': [0, 0],
                        'name': 'The Junction',
                        'relationships': {   'aether_syndicate': 'Neutral',
                                             'iron_pioneers': 'Neutral',
                                             'neon_runners': 'Neutral',
                                             'scrap_vultures': 'Neutral',
                                             'the_junction': 'Neutral'},
                        'units': ['Vehicle']}}
