FACTION_DATA = {   'aegis_dynamics': {   'control': 50,
                          'description': 'A militaristic corporation that '
                                         'believes order can only be forged '
                                         'through superior firepower and '
                                         'absolute control.',
                          'faction_boss': {   'damage_multiplier': 2.5,
                                              'hp_multiplier': 6.0,
                                              'name': 'Warlord Kael',
                                              'vehicle': 'WarRig'},
                          'hub_city_coordinates': [4000, 4000],
                          'name': 'Aegis Dynamics',
                          'relationships': {   'cog_lords': 'Hostile',
                                               'omni_corp': 'Hostile',
                                               'rust_devils': 'Hostile',
                                               'the_exchange': 'Neutral'},
                          'units': ['Technical', 'GuardTruck', 'WarRig']},
    'cog_lords': {   'control': 50,
                     'description': 'Master mechanics and engineers who have '
                                    'turned scrap into monstrously powerful, '
                                    'custom-built war machines.',
                     'faction_boss': {   'damage_multiplier': 1.5,
                                         'hp_multiplier': 7.0,
                                         'name': 'The Foreman',
                                         'vehicle': 'Miner'},
                     'hub_city_coordinates': [-3000, 5000],
                     'name': 'Cog Lords',
                     'relationships': {   'aegis_dynamics': 'Hostile',
                                          'omni_corp': 'Neutral',
                                          'rust_devils': 'Neutral',
                                          'the_exchange': 'Neutral'},
                     'units': ['Truck', 'PanelWagon', 'Miner']},
    'omni_corp': {   'control': 50,
                     'description': 'A remnant corporation that hoards '
                                    'pre-apocalypse technology, viewing '
                                    'salvage as their exclusive right.',
                     'faction_boss': {   'damage_multiplier': 2.0,
                                         'hp_multiplier': 5.5,
                                         'name': 'Director Valerius',
                                         'vehicle': 'ArmoredTruck'},
                     'hub_city_coordinates': [-4000, -4000],
                     'name': 'OmniCorp',
                     'relationships': {   'aegis_dynamics': 'Hostile',
                                          'cog_lords': 'Neutral',
                                          'rust_devils': 'Hostile',
                                          'the_exchange': 'Neutral'},
                     'units': ['Sedan', 'Peacekeeper', 'Hatchback']},
    'rust_devils': {   'control': 50,
                       'description': 'Territorial and fiercely independent '
                                      'scavengers who thrive in the '
                                      'scrapyards, seeing the corporations as '
                                      'invaders.',
                       'faction_boss': {   'damage_multiplier': 3.0,
                                           'hp_multiplier': 3.5,
                                           'name': 'Saw-Tooth',
                                           'vehicle': 'RaiderBuggy'},
                       'hub_city_coordinates': [3000, -3000],
                       'name': 'Rust Devils',
                       'relationships': {   'aegis_dynamics': 'Hostile',
                                            'cog_lords': 'Neutral',
                                            'omni_corp': 'Hostile',
                                            'the_exchange': 'Neutral'},
                       'units': ['RaiderBuggy', 'RustySedan', 'Technical']},
    'the_exchange': {   'control': 100,
                        'description': 'The last bastion of neutrality. A '
                                       'sprawling, fortified marketplace built '
                                       'around a salvaged comms tower, where '
                                       'credits are the only true allegiance.',
                        'faction_boss': None,
                        'hub_city_coordinates': [0, 0],
                        'name': 'The Exchange',
                        'relationships': {   'aegis_dynamics': 'Neutral',
                                             'cog_lords': 'Neutral',
                                             'omni_corp': 'Neutral',
                                             'rust_devils': 'Neutral'},
                        'units': ['Sedan', 'Truck', 'Hatchback']}}
